---
title: "End of my internship at LLR"
date: 2026-07-01
---

Yesterday, on June 30, I presented the results of my 5 month internship at the LHCb team of Laboratoire Leprince-Ringuet at the weekly simulation meeting of the LHCb collaboration of CERN. 

This presentation marks the end of my internship, and I have mixed feelings. Needless to say, working on particle physics has been a dream as long as I can remember, and I feel proud to say I was a part of the researchers working at CERN. But it was also surprising in ways that I did not expect.

First of all, the particle physics *phenomenology* research has a completely different structure from what I experienced before. My previous intership was at the Irradiated Solids Laboratory of Polytechnique. Whether the work is hands-on experiments or running simulations on a computer, the structure was that you would find yourself an interesting question, and spend months trying to answer that with at most 5-10 people that you keep contact about the specific subject. For LLR, it was a lot different: There were people from literally all around the world, constantly emailing each other or giving presentations. Each team was focusing on a very small detail of a very small subsection of the entire experiment, and all these people were coming together to run the biggest man-made machine. The information was so structurally organized, and very neatly formatted. It was impossible for any work that is done by some team to be missed by another team and replicated. From what I've seen so far, this was the only real example of *collaboration* in research, and all the other research groups in other fields act as individuals compared to the particle physics people.

Second issue was the fact that my internship felt more like a *programming* internship than a *physics* one. I was sitting in the office all day, writing data analysis code and generating plots. As a matter of fact, the first few weeks of my internship was just me learning how to access the virtual machines and trying to remember to do `bash` everytime I logged in. I still don't know why I need to do that... But to be honest, this *issue* would not be an issue if it wasn't for the next thing I'm going to mention, which is the fact that I didn't know particle physics.

Of course, it would be unreasonable to expect a second year undergraduate student to know particle physics to the point that they would understand everything they are doing. The researchers working on particle physics are aware of this. For that reason, whenever an undergraduate student arrives at their lab looking for an internship, they just tell the student that they do not need to understand everything, and that they would be just fine as long as they know some Python and how to ask stuff to ChatGPT. Is this a healty way of approaching to an internship? Well, there is not really any other option for the researchers. They can't teach the student high energy physics theory in the time frame of "4 hours every week for 5 months". Let alone teaching actual particle physics, they can't even get through all of the prerequisites. At this point, however, I think the student should be able to make an informed decision. In my situation, I was a little lost in the excitement of working at CERN, and I didn't really think much about what I would be learning from this internship. In the end, I can't say I didn't learn anything. I learned a lot about how the reserach worked, a lot of basic information about how the experiments are combined with simulations, how the simulated data is generated, etc. However, I can't keep myself from thinking, would I have learned more if I did an internship that was more suitable for my level and skills? Probably yes...

With all these said, I genuinely think that this internship was a valuable experience for me. I think that it would be even more valuable if I had intentions of working in experimental particle physics in my later life. I have friends with such plans, and they absolute love the time they spend doing this kind of work. What I can suggest to people interested in this type of internship is that they should carefully think through what they want to do after they graduate, and choose their internships according to their goals. After all, one can fit only a few internships in their undergraduate education, especially if it's three years long.

Anyways, the report from my intership and the presentation slides from the defense are below, in case anyone is interested in seeing how a research project in particle physics without knowing any particle physics looks.

[Validation of the Fast Calorimeter Simulation in LHCb Fixed-Target Collisions](../files/Validation of the Fast Calorimeter Simulation in LHCb Fixed-Target Collisions.pdf)

[Slides](../files/PRL_Presentation.pdf)